apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      multiCluster:
        # Provided to ensure a human readable name rather than a UUID.
        clusterName: "cn-qwiklabs-gcp-04-08a88f0e68d5-us-west1-c-cluster-1" # {"$ref":"#/definitions/io.k8s.cli.substitutions.cluster-name"}
