apiVersion: v1
kind: Service
metadata: # kpt-merge: default/tf-serving
  name: tf-serving
  namespace: default
  labels:
    app: tf-serving
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|tf-serving'
spec:
  type: ClusterIP
  #type: LoadBalancer
  ports:
  - port: 8500
    protocol: TCP
    name: tf-serving-grpc
  - port: 8501
    protocol: TCP
    name: tf-serving-http
  selector:
    app: tf-serving
